### PR TITLE
Bring Ruby 2.3.1 into omnibus toolchain

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by scotthain** [comment]
@chef/engineering-services

**Comment by scotthain** [comment]
I'm 👎 on pointing at branches unless there is a dependency on the toolchain ruby version that blocks us moving *off* said branches. (in the which case that is... scary and we should fix that pronto)

**Comment by mwrock** [comment]
LGTM :+1:

**Comment by mwrock** [comment]
yeah the branches have gotten out of control @scotthain but that is the next thing we want to tackle after finishing the ruby 2.3.1 rollout

**Comment by mwrock** [comment]
I dont think we want to block this on that.

**Comment by scotthain** [comment]
👍 pending final e2e test - thanks @jkeiser

**Pull request merged**
