### PR TITLE
Empty commit - forcing pacman rebuild

### PR DESCRIPTION
**Pull request by chef-delivery**
This Pull Request was opened by Chef Automate user Scott Hain

Signed-off-by: Scott Hain <shain@chef.io>

Ready to merge? View this change in Chef Automate and click the Approve button: https://automate.chef.co/e/chef/#/organizations/engineering-services/projects/omnibus-toolchain/changes/b78dabcc-f0d2-4acd-ae15-6476ed032026

### CODE REVIEW

**Comment by scotthain** [comment]
@chef/engineering-services @stevendanna

**Comment by schisamo** [comment]
@scotthain How is this different than https://github.com/chef/omnibus-toolchain/pull/60?

**Comment by scotthain** [comment]
@schisamo this one came from workflow so it will trigger the builds...

**Comment by stevendanna** [comment]
👍 Let's do it.

**Comment by schisamo** [comment]
I'm going to close this as we can now merge https://github.com/chef/omnibus-toolchain/pull/63 which gets this repo off Workflow and will automatically kick off the new build by way of Expeditor.

**Pull request closed without merging**
